### PR TITLE
Adds support for Laravel 11 and PHP 8.x

### PR DESCRIPTION
**Pull request by wlhrtr**
## Summary

Updates composer json to support Laravel 11 and PHP 8.x

### CODE REVIEW

**Comment by bucari** [comment]
@asantibanez can you merge this pull request please?

**Comment by wlhrtr** [comment]
@asantibanez it looks like you kinda abandoned this package.

I would appreciate if we could integrate those changes as I am currently working on a project with this package locally imported.

Some other features like transition validations and more general hooks got added by me but I am hesitant to create PRs for those features as of the silentness around them.

I would love to help you with those PRs or if we could have a chat on how we could re-alive this repo.

If you say you do not want to continue the development of this package, it's ok, then I will publish my changes in my fork and create a new package. But as said, would love to keep it here and continue development of this package.

**Comment by yuriimakarov** [comment]
Hello @asantibanez, could you please review an update from @wlhrtr i also use this package and want to update to Laravel 11

**Comment by bucari** [comment]
@wlhrtr i think you should create a new package

**Comment by wlhrtr** [comment]
Sorry for the delay guys. Needed this package in my job but other things got prioritized.

I now got back to our state machine refactor and have now published an new package based on this master plus the compatibility PR. New features will follow.

https://github.com/wlhrtr/state-machine

It should be a drop-in replacement except that you have to update the namespaces.

Please create an issue if something is not working as expected.

**Comment by nkhoangvu** [comment]
I am also waiting so long for this package to be updated. Thank @wlhrtr so much for your package, it works like a charm after updating the name space.

**Pull request closed without merging**
